import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/css/globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <Toaster />
        <Navbar/>
        
        {children}
        
        </body>
    </html>
  );
}
